version: '2'
networks:
  default:
    external:
      name: ggggg
services:
  php74:
    image: registry.cn-zhangjiakou.aliyuncs.com/xssg/phpdhtspider:laster
    privileged: false
    restart: unless-stopped
    container_name: phpdhtspider_client
    environment:
      - SERVER_IP:frpchk
    command:
      - php
      - go_client.php
    volumes:
      - ./logs:/var/www/html/dht_client_task/logs
    ports:
      - 31739:31739